build:
    environment:
        php: 7.4

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths:
        - src/
    dependency_paths:
        - vendor/
    excluded_paths:
        - tests/

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 300
        runs: 1
